USE [DQ]
GO
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Active Customer Count')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Valid Customer Count')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('New Customer Count')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('New Logo Customer Count')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Deployed Customer Count')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('New Logo Customer Count for Past 12M')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Partner Retention Rate (YoY)')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Lost Customer Count for Past 12M')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Lost Customer Count')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Retention Rate of Active Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Retention Rate of Valid Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Years of Loyalty')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Avg. Customer Annual Value')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Total Customer Annual Value')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Valid Seat Count')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Revenue Retention Rate of Valid Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Revenue Retention Rate of Active Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Net Revenue Retention Rate of Valid Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Net Revenue Retention Rate of Active Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Deployed Instance Count')
INSERT INTO [DQ].[dbo].[Cube_Unhidden_Measure]([Measure]) VALUES ('Deployed Device Count')
