USE [DQ]
GO
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count Control_NCCT_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count Control_NCCT_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Customer Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count Type control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count control_M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Customer Count Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count Control_NCCT_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DEFAULT - New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('YL - New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DEFAULT - New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('YL - New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('YL - New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DEFAULT - New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DEFAULT - S_New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - S_New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - S_New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - S_New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - S_New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('YL - S_New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - S_New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_New Customer Count_L0')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DEFAULT - S_New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - S_New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - S_New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - S_New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - S_New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('YL - S_New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - S_New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_New Customer Count_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DEFAULT - S_New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - S_New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - S_New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - S_New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - S_New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('YL - S_New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - S_New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_New Customer Count_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count Type control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Customer Count control_M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Customer Count Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count for Past 12M')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Product Retention Rate of Active Customers (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Product Retention Rate of Valid Customers (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Partner Retention Rate (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Active Customers (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Valid Customers (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Partner Retention Rate (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Product Lost Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count for Past 12M Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count for Past 12M Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Active Customers (YoY) Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Valid Customers (YoY) Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Partner Retention Rate (YoY) Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count for Past 12M')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Active Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Valid Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Active Customers (YoY) Control_SP_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Valid Customers (YoY) Control_SP_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count Control_SP_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count for Past 12M Control_SP_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Valid Customer Count (YoY)_Default')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Product Retention Rate of Active Customers (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Product Retention Rate of Valid Customers (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Active Customers (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Valid Customers (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Partner Retention Rate (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Product Lost Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('New Logo Customer Count for Past 12M Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count for Past 12M Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Lost Customer Count Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Active Customers (YoY) Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Retention Rate of Valid Customers (YoY) Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Partner Retention Rate (YoY) Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Years of Loyalty_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Years of Loyalty')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Years of Loyalty_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Avg. Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Total Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Annual Value LY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Annual Value LY_Base Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Annual Value CY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Annual Value LY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Annual Value LY_Base Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Annual Value CY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Avg. Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Avg. Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Avg. Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Avg. Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Total Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Total Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Total Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Total Customer Annual Value_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 CAV LY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB CAV LY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 CAV LY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT CAV LY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 CAV LY_Base Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB CAV LY_Base Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 CAV LY_Base Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT CAV LY_Base Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 CAV CY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB CAV CY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 CAV CY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT CAV CY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 CAV LY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB CAV LY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 CAV LY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT CAV LY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 CAV LY_Base Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB CAV LY_Base Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 CAV LY_Base Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT CAV LY_Base Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 CAV CY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB CAV CY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 CAV CY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT CAV CY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Avg. Customer Annual Value Control_NCCT_P')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Total Customer Annual Value Control_NCCT_P')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Avg. Customer Annual Value Control_NCCT_S')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Total Customer Annual Value Control_NCCT_S')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Avg. Customer Annual Value')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Total Customer Annual Value')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Seat Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Seat Count Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Seat Count Control_NCCT_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Valid Seat Count Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Avg. Customer Annual Value - Suite')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Total Customer Annual Value - Suite')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Customer Annual Value LY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Customer Annual Value LY_Base Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Customer Annual Value CY_Retain Valid Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Customer Annual Value LY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Customer Annual Value LY_Base Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Customer Annual Value CY_Retain Active Customer_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Revenue Retention Rate of Valid Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Revenue Retention Rate of Active Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Net Revenue Retention Rate of Valid Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Net Revenue Retention Rate of Active Customers (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Revenue Retention Rate of Valid Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Revenue Retention Rate of Active Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Net Revenue Retention Rate of Valid Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Net Revenue Retention Rate of Active Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Revenue Retention Rate of Valid Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Revenue Retention Rate of Active Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Net Revenue Retention Rate of Valid Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Customer Net Revenue Retention Rate of Active Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Revenue Retention Rate of Valid Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Revenue Retention Rate of Active Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Net Revenue Retention Rate of Valid Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_Net Revenue Retention Rate of Active Customer (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Valid - L2_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Valid - Seat Range - Valid_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Valid - Solution Combination_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Valid - CAV Range L2 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Valid - CAV Range L1 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Valid - L2_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Valid - Seat Range - Valid_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Valid - Solution Combination_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Valid - CAV Range L2 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Valid - CAV Range L1 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Valid - L2_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Valid - Seat Range - Valid_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Valid - Solution Combination_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Valid - CAV Range L2 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Valid - CAV Range L1 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Active - L2_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Active - Seat Range - Valid_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Active - Solution Combination_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Active - CAV Range L2 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_CY_Retain Active - CAV Range L1 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Active - L2_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Active - Seat Range - Valid_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Active - Solution Combination_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Active - CAV Range L2 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Retain Active - CAV Range L1 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Active - L2_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Active - Seat Range - Valid_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Active - Solution Combination_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Active - CAV Range L2 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('S_CAV_LY_Base Active - CAV Range L1 (Suite)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_L2 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_L1 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_L0 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC_L2 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC_L1 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC_L0 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC_Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('V_Range_L2 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('V_Range_L1 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('V_Range_L0 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid_L2 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid_L1 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid_L0 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count LM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count LM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count LM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count LQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count LQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count LQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_L0 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_L1 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_L2 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('P_Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC_Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC_L2 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC_L1 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC_L0 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('V_Range_L2 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('V_Range_L1 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('V_Range_L0 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid_L2 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid_L1 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid_L0 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count LM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count LM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count LM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count LQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count LQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count LQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L2 Deployed Seat Count LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L1 Deployed Seat Count LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('D_Range_L0 Deployed Seat Count LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L2 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L1 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L0 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L2 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L1 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L0 Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Active Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('No_of_P_Active Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L2 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L1 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L0 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L2 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L1 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L0 Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT Active Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Active Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L2 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L1 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L0 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L2 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L1 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L0 Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L2 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L1 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB_L0 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_SB Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L2 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L1 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT_L0 Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed Cross P_ENT Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('No_of_P_Valid Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('No_of_P_Valid Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Active Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('AR - P_Valid Customer Count (YoY)_L1')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('AR - P_Valid Customer Count (YoY)_L2')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - P_Valid Customer Count (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid P_Valid Customer Count (YoY)')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Active Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('No_of_P_Deployed Customer Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Deployed Customer Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT PTR_Valid Customer Count (YoY)_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT PTR_Valid Customer Count LM_LY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Product Lost Customer Count for Past 12M_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Lost Customer Count byM_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Lost Customer Count byQ_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Lost Customer Count byY_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT PTR_Valid Customer Count (YoY)_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT PTR_Valid Customer Count LM_LY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Product Lost Customer Count for Past 12M_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Lost Customer Count byM_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Lost Customer Count byQ_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT P_Lost Customer Count byY_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Valid Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L2 Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L1 Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB_L0 Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed SB Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L2 Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L1 Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT_L0 Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Deployed ENT Valid Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Instance Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Seat Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Instance Count Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Device Count_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Device Count')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Device Count Control_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Seat Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Instance Count Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Device Count_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deployed Device Count Control_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deploy Device Count CV_S_L2_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deploy Device Count CV_S_L2_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deploy Device Count CV_S_L1_All')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Deploy Device Count CV_S_L1_Org')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Default_P_Lost Customer Count_M')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - P_Lost Customer Count_M')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - P_Lost Customer Count_M')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid P_Lost Customer Count_M')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - P_Lost Customer Count_M')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - P_Lost Customer Count_M')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Default_P_Lost Customer Count_Q')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - P_Lost Customer Count_Q')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - P_Lost Customer Count_Q')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid P_Lost Customer Count_Q')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - P_Lost Customer Count_Q')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - P_Lost Customer Count_Q')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Default_P_Lost Customer Count_Y')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - P_Lost Customer Count_Y')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - P_Lost Customer Count_Y')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid P_Lost Customer Count_Y')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - P_Lost Customer Count_Y')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - P_Lost Customer Count_Y')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('Default_P_Lost Customer Count_LMLY')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL1 - P_Lost Customer Count_LMLY')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('ARL2 - P_Lost Customer Count_LMLY')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SR - Valid P_Lost Customer Count_LMLY')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('SC - P_Lost Customer Count_LMLY')
INSERT INTO [DQ].[dbo].[Cube_All_Measure]([Measure]) VALUES ('DS - P_Lost Customer Count_LMLY')
